export enum DefaultGrammarRuleLabel {
  StartRule = "start",
  LogicalOrRule = "logicalOr",
  LogicalAndRule = "logicalAnd",
  ConditionRule = "condition",
  ComparisonOperatorRule = "comparisonOp",
  BooleanTermRule = "booleanTerm",
  TerminalRule = "terminal",
  TerminalObjectLiteralRule = "terminalObjectLiteral",
  TerminalObjectRule = "terminalObject",
  TerimalObjectKeyValuePairRule = "terminalObjectKeyValuePair",
  TerminalListLiteralRule = "terminalListLiteral",
  TerminalListRule = "terminalList",
  BooleanRule = "boolean",
  NumberRule = "number",
  StringRule = "string",
  IdentifierRule = "identifier",
}
